### ISSUE TITLE
{Apache 2.0} breaks the page

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1196] opened 2020-04-11 16:19 UTC
Funny thing: If I put the text `{Apache 2.0}` in a page, it breaks 🤔 (`{2}` breaks it too)

![image](https://user-images.githubusercontent.com/1673303/79048938-12eeef80-7c53-11ea-97ae-68fc5d8d04e9.png)

**Comment by ang-zeyu** [comment] 2020-04-11 16:45
Where was this placed? 
[markdown-it-attrs](https://www.npmjs.com/package/markdown-it-attrs) would recognise single curly braces as "attributes", though I'm not so sure how it breaks the page

For a workaround could try `<span>{</span>apache 2.0<span>}</span>` temporarily
A permanant component to "escape everything and have it show in the browser" is in the works https://github.com/MarkBind/markbind/pull/1049#issuecomment-592963453

**Comment by damithc** [comment] 2020-04-11 17:33
Putting it in any page in the CS2113 website seems to break the page. Only certain cases break. e.g., `{abc}` does not cause problems.
Thanks for the workaround. It's fine if the fix is on the way.

**Comment by ang-zeyu** [comment] 2020-04-12 14:47
investigated it a little more just to be sure;

the html generated is as expected from markbind's standpoint; it only breaks when there are numbers as starting characters of the attributes e.g. `2.0` in `apache 2.0` or `2`, which isn't allowed by the browser

```html
<p apache="" 2.0=""></p>
```


will close this since the problem is the same as #762 otherwise

**Closed by ang-zeyu** 2020-04-12 14:47 UTC
Labels: s.ToInvestigate

**Comment by damithc** [comment] 2020-04-12 15:37
> will close this since the problem is the same as #762 otherwise

Not quite the same though, at least from the author POV. Nunjucks doesn't have a `{x}` syntax (it uses double braces). So, the author will not realize the text is likely to cause problems. We often use `{ abc }` as placeholders in document templates e.g., `{your product name here}`

**Comment by ang-zeyu** [comment] 2020-04-12 16:57
ahh ok, the solution to both the problems would be the same though ( some sort of `<escape>...</escape>` component )
Since `markdown-it-attrs` isn't mentioned explicitly in the ug, we could particularly highlight this in #1106 meanwhile
