### ISSUE TITLE
Site gets stuck in a perpetual loading stage

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#915] opened 2019-06-28 07:32 UTC
At times, MarkBind sites get stuck in a perpetual 'loading' stage, although the site is fully usable.

Env: chrome, Windows

Example:
![loading](https://user-images.githubusercontent.com/1673303/60325405-cd11b500-99b9-11e9-9cb1-d8bdc4d2e6e5.gif)

**Comment by Chng-Zhi-Xuan** [comment] 2019-06-28 08:25
Is there a specific page that triggered this? I can't reproduce it.

**Comment by damithc** [comment] 2019-06-28 08:41
It cannot be reproduced reliably. Happens randomly.

**Comment by ang-zeyu** [comment] 2022-01-14 13:35
closing this until reproducible realiably; might also have been fixed somewhere along the way / or a browser / server issue

**Closed by ang-zeyu** 2022-01-14 13:35 UTC
Labels: p.Low, a-FaultTolerance, s.ToInvestigate
