### ISSUE TITLE
Code snippets: text in angle brackets become lowercase

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#101] opened 2017-09-24 03:38 UTC
For example `<Person>` becomes `<person>` after rendering to html. 
The current workaround is to add extra spaces `< Person >` which stays as `< Person >` after rendering.

**Comment by damithc** [comment] 2018-01-11 05:29
It is also causing problems for operators such as `>=`

**Comment by nicholaschuayunzhi** [comment] 2018-01-17 15:47
I would like to try this issue but am having problems with reproducing the bug.

I tried this
~~~
```
<Person>
```
~~~
But it renders as 
![image](https://user-images.githubusercontent.com/22221132/35051681-c5a8c1c8-fbe0-11e7-9b30-0f05b927c4cf.png)

**Comment by acjh** [comment] 2018-01-17 16:26
The example in the description can be found here:
Admin > v1.5rc [week 12] > Tips: how to score high for code quality > code quality guidelines covered in the module > Guideline: Name Well > Basic > Use Nouns for Things and Verbs for Actions

`ArrayList<Person> students` becomes `ArrayList<person> students`

**Comment by damithc** [comment] 2018-01-18 02:49
Sometimes it can even break the whole page. It seems angle brackets inside code snippets are being interpreted as instructions to the parser rather than being ignored as plain text.

Another example where the problem occurs if I use `<words>` instead of `< words >`
```
>>> type(True)
< class 'bool' >

>>> type(False)
< class 'bool' >

>>> type('True')
< class 'str' >
```

**Comment by danielbrzn** [comment] 2018-01-20 03:54
It seems like this is a problem with the htmlparser2 library that Markbind is using. This is in https://github.com/fb55/htmlparser2/issues/220 and it does not seem that it will be fixed.

Should we consider changing to another HTML parser library like https://github.com/inikulin/parse5 or should we fork htmlparser2 and try to fix it ourselves?

**Comment by Gisonrg** [comment] 2018-01-20 04:33
I think htmlparser2 is not actively maintained and buggy as well...
However changing to another HTML parser library could easily worth a few weeks' efforts and basically a re-rewrite of the parser. Let's create an issue to track this.

**Comment by danielbrzn** [comment] 2018-01-23 20:18
I managed to fix it by modifying the behaviour of htmlparser2 for Markdown code, but I suppose it would require a fork of htmlparser2 with our own modifications. What does everyone think?

![image](https://user-images.githubusercontent.com/251231/35298573-8d636cc8-00bd-11e8-87c1-7b7b6e3078bc.png)

**Comment by damithc** [comment] 2018-01-24 03:07
Nice work @nicholaschuayunzhi .
It depends on how extensive the patch is and how reliable the fix is. 
It also depends on how active their repo is. If it is active, we can submit a PR and get it merged so that we can discard our own fork and go back to using the upstream version at some point in future.
On the other hand if the repo is dead, we can use our own fork for the time being (with your fix) but for the longer term we might have to find a replacement library anyway.

**Comment by nicholaschuayunzhi** [comment] 2018-01-24 03:08
@damithc , I think you should credit @danielbrzn, he did the work.

**Comment by acjh** [comment] 2018-01-24 03:52
Creating a fork for this fix sounds reasonable, since the repo is dead.
This means that MarkBind will need to publish our fork on npm, right?

This is a case where a test in #121 would be necessary, for when we change the parser in the future.
As discussed, that change is on hold — considering that `cheerio` depends on `htmlparser2` as well.

**Comment by damithc** [comment] 2018-01-24 04:19
> @damithc , I think you should credit @danielbrzn, he did the work.

Yup, sorry.

**Comment by danielbrzn** [comment] 2018-01-24 05:16
@damithc 
It's a very small fix that forces the parser to treat markdown code like `x<y` as text instead of having it parse the information in between the quotes. This allows the markdown code to remain as is until we call the markdown renderer to properly render it to HTML. When testing using the live site, it seems that everything renders properly but there was a small change that I had to make to [website\admin\appendixB-polices.md](https://github.com/nus-cs2103-AY1718S2/website/blob/master/admin/appendixB-policies.md) as there was an extra ' ` ' character at the end of the stackoverflow link under the section "giving credit for reused work". This extra character was causing the fixed parser to not be able to properly resolve the base URLs.

@acjh 
Actually, it seems that the developer has returned. However, he did [mention ](https://github.com/fb55/htmlparser2/issues/220)to use [parse5 ](https://github.com/inikulin/parse5)if a spec-compliant parser was necessary. 

I feel that the fix that I have is quite specific to our project and I'm not sure if it would be appropriate to submit it as a PR to the upstream version.

**Comment by acjh** [comment] 2018-01-24 05:38
@danielbrzn Noted. But isn't it specific to Markdown-in-HTML, rather than MarkBind?

> This means that MarkBind will need to publish our fork on npm, right?

@Gisonrg Shall I set up a repo for this?

**Comment by danielbrzn** [comment] 2018-01-24 05:44
@acjh Ah yes, that's true. I guess we could consider making a PR to the upstream repo.

About publishing our fork on npm, how about we have it as a [private module](https://techsparx.com/nodejs/deployment/non-npm-packages.html)?

**Comment by acjh** [comment] 2018-01-24 05:55
Ah yes, a private module.

**Comment by damithc** [comment] 2018-01-24 06:03
@danielbrzn 
See the following part in https://nus-te3201.github.io/website/programming/index.html#program-flow-control
![image](https://user-images.githubusercontent.com/1673303/35316921-203c573e-010f-11e8-87db-7f3de303042c.png)

I had to do this ugly workaround because of this issue. See if your fix works for this code too.
The code is at https://github.com/nus-te3201/website

Specifically, https://github.com/nus-te3201/website/blob/master/programming/booleans/text.md

**Comment by danielbrzn** [comment] 2018-01-24 06:14
@damithc 

Seems like it works!

![image](https://user-images.githubusercontent.com/251231/35317242-cfe01c06-0110-11e8-8af3-ba199e2a842b.png)

**Comment by damithc** [comment] 2018-01-24 06:33
> Seems like it works!

Nice.

**Comment by acjh** [comment] 2018-01-25 03:30
Forked to [MarkBind/htmlparser2](https://github.com/MarkBind/htmlparser2)

**Closed** 2018-02-03 18:32 UTC
Labels: p.High
