### ISSUE TITLE
Support slots for box components

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1492] opened 2021-02-26 09:34 UTC
This should work, right?
```html
<box>
<span slot="header" class="card-title">Python tip</span>

some content here

</box>
```

Output I get
![image](https://user-images.githubusercontent.com/1673303/109282853-0d919800-7859-11eb-8ccb-9d19a282b957.png)

**Comment by wxwxwxwx9** [comment] 2021-02-26 11:02
Took a quick look at this. The issue stems from the mismatch in the slot name. If we were to use `slot="_header"`, it would work. The slot name we are using in the Vue component like box and tabs are using `_header` as the slot name. 

I think the issue can be solved by transforming the `header` slot into `_header` in the node processing stage. However, I think there may be a reason why we are using the `_header` slot name in some of our Vue components instead of just `header`, and I'm not sure what's the reason. 

@ang-zeyu can I clarify why is the above necessary? :-)

**Comment by ang-zeyu** [comment] 2021-02-26 13:16
> I think the issue can be solved by transforming the header slot into _header in the node processing stage.

I think this was being done at one point (or it might have been mislabelled as supported but actually not), I can't really recall =(
It should be fixed eitherway.

`_xx` was intended as originally intended as internal naming for slots resulting from attributes.

On a separate note, I think we could move toward just `xx`, I haven't observed much benefit from the duplicate `_xx` slot - if anything it results in some duplicate templates

**Closed** 2021-04-29 08:48 UTC
Labels: c.Bug 🐛, d.easy, f-Box, p.High
