### ISSUE TITLE
Panel not expanding due to extra spaces in the table above it

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#2182] opened 2023-02-21 12:47 UTC
Context: See https://nus-tee3201.github.io/2023/schedule/week5/topics-py.html#exercise-shorten-string

This panel was not opening when clicked.
![image](https://user-images.githubusercontent.com/1673303/220347077-b8a0e3e7-6985-4e9b-bcd7-e77429ec0773.png)

Furthermore, all `partial solution` panels that appeared in the sections below it had the same problem.

By tinkering around, I managed to fix it by removing these indentations in the code for the table just above it (see diff for details): https://github.com/nus-cs2103/website-base/commit/0fef291042be6763ee129549b2d5a3094eec4443

Interestingly, it fixed the problem for all panels below it too. So, all is well now but I'm curious why it happened in the first place.

The relevant code base is https://github.com/nus-cs2103/website-base
It is a variant of the CS2103 website. After cloning and pulling the sub-module, switch to the `tee3201` branch before running `markbind serve`.

Let me know if you need more info.

**Comment by tlylt** [comment] 2023-03-06 04:46
Seems like a case of invalid HTML -> hydration issue -> malfunction of components. This tends to impact all components on the same page, below the point of incident, and fixable by fixing the cause of invalid HTML.

**Comment by damithc** [comment] 2023-03-06 05:06
> Seems like a case of invalid HTML -> hydration issue -> malfunction of components. This tends to impact all components on the same page, below the point of incident, and fixable by fixing the cause of invalid HTML.

@tlylt Yeah, similar to some other cases we had before.
But in this case, how come the extra indentation made HTML invalid? 
Also, users will find this kind of problems very puzzling, right? Is there any way to make the behavior more forgiving?

**Comment by tlylt** [comment] 2023-03-06 05:35
Yes this is related to the missing `tbody` [issue](https://github.com/MarkBind/markbind/issues/2025#issue-135388434) that we have experienced before. The complete fix as suggested in the comments is to add a `<tbody>` wherever we manually construct a HTML `<table>`. @damithc I think you might have missed these out due to the newline and extra indentation.

> But in this case, how come the extra indentation made HTML invalid?

I just pulled the repository and strangely the panels seem to work fine locally without the update you made.
- when i open my local copy of website-base\programming\strings-workingWith\e-shortenString.md after switching to the `ay2122s2-tee3201` or `te3201` branch (there is no `tee3201` branch), the content is still:
```
Example usage:
<table> 
<tr>
  <td>

something here
  </td>
  <td><br>&nbsp;→&nbsp;</td>
  <td><br>
something here

  </td>
</tr>
</table>
```

- the panels when clicked does open
- It does show the warning about missing body tho, likely due to the boilerplate in [_markbind\boilerplates\inputOutput.md](https://raw.githubusercontent.com/nus-cs2103/website-base/master/_markbind/boilerplates/inputOutput.md)

I might need to dig deeper to find out the root cause for this one after I'm able to reproduce a case that the panel no longer works.

> Also, users will find this kind of problems very puzzling, right? Is there any way to make the behavior more forgiving?

Yes, I think we should log a warning somewhere, will need some research into how we can detect and capture the error.

**Comment by damithc** [comment] 2023-03-06 14:57
> * when i open my local copy of website-base\programming\strings-workingWith\e-shortenString.md after switching to the `ay2122s2-tee3201` or `te3201` branch (there is no `tee3201` branch), the content is still:

@tlylt  Sorry, I realized I don't push the `tee3201` branch to that repo. It can be found in https://github.com/nus-tee3201/2023
The `<tbody>` tag was there in that table already.

**Comment by ang-zeyu** [comment] 2023-04-26 10:50
https://github.com/MarkBind/markbind/issues/2076

**Comment by ang-zeyu** [comment] 2023-04-26 10:51
Closed this for now since the problem has been found.

**Closed** 2023-04-26 10:51 UTC
Labels: c.Bug 🐛, s.ToInvestigate
