### ISSUE TITLE
Tooltips seem to add an extra space in front

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#2419] opened 2024-02-14 12:27 UTC
code: `(<tooltip content="abc">why?</tooltip>)`
output:
![image](https://github.com/MarkBind/markbind/assets/1673303/959fd298-ec2c-401c-8532-aa4dda5a6736)

problem: there is an extra space between `(` and `w`?

PS: noticed the same issue with popevers

![image](https://github.com/MarkBind/markbind/assets/1673303/edcaa5bd-9b92-415d-8a83-9b782ccf5fb6)

**Comment by kaixin-hc** [comment] 2024-02-14 21:31
Did some investigating, though couldn't find the root cause yet:

VERY similar issue surfaced in the past: #569 - resolved by [this PR](https://github.com/MarkBind/vue-strap/pull/111/files#diff-96102908b73808d79ed57fa960c8f7132e705528bf49119322247c698c72f94b) in vue-strap, which removed the new lines which were being processed as a space. (Interestingly, [the PR here](https://github.com/MarkBind/vue-strap/commit/96adcfb15cc90d7ccba796ab5771267eccfdef9a#) removes the line of code in tooltip that removes the new line in front added in #569 - which I thought might be why there's an additional space in front, but not behind).  However, vue-strap was migrated into MarkBind in #1248 - though the PR doesn't seem to show the Tooltip file - and I can't seem to find this code in MarkBind.

That aside, it seems Tooltip was wholly rewritten in #1748 and later amended again in #1868 to use floating-vue. With this different implementation, maybe it is some other problem?

(FYI, the solution in https://markbind.org/userGuide/tipsAndTricks.html#unwanted-starting-space-in-links-and-triggers does not solve this issue.)

**Comment by damithc** [comment] 2024-02-15 03:43
Noticed the same issue with popovers

![image](https://github.com/MarkBind/markbind/assets/1673303/55a1656e-2bd3-4d51-a154-42656077387d)

**Comment by yiwen101** [comment] 2024-03-30 13:47
> Did some investigating, though couldn't find the root cause yet:
> 
> VERY similar issue surfaced in the past: #569 - resolved by [this PR](https://github.com/MarkBind/vue-strap/pull/111/files#diff-96102908b73808d79ed57fa960c8f7132e705528bf49119322247c698c72f94b) in vue-strap, which removed the new lines which were being processed as a space. (Interestingly, [the PR here](https://github.com/MarkBind/vue-strap/commit/96adcfb15cc90d7ccba796ab5771267eccfdef9a#) removes the line of code in tooltip that removes the new line in front added in #569 - which I thought might be why there's an additional space in front, but not behind). However, vue-strap was migrated into MarkBind in #1248 - though the PR doesn't seem to show the Tooltip file - and I can't seem to find this code in MarkBind.
> 
> That aside, it seems Tooltip was wholly rewritten in #1748 and later amended again in #1868 to use floating-vue. With this different implementation, maybe it is some other problem?
> 
> (FYI, the solution in https://markbind.org/userGuide/tipsAndTricks.html#unwanted-starting-space-in-links-and-triggers does not solve this issue.)

Thank you for your investigation, this is indeed the true cause; 

<img width="823" alt="Screenshot 2024-03-30 at 21 43 38" src="https://github.com/MarkBind/markbind/assets/121547057/d5c806f6-92e9-4879-864e-664e4b98a1c0">
<img width="62" alt="Screenshot 2024-03-30 at 21 43 50" src="https://github.com/MarkBind/markbind/assets/121547057/9002a685-5306-4167-a0aa-622a271672e0">
After (ugly, temporarily) putting everything together leaving not space in between, the extra space disappears

**Closed** 2024-04-04 10:18 UTC
Labels: s.ToInvestigate
