### ISSUE TITLE
Incorrect behavior for minimal panel transition

### ISSUE THREAD

**Issue by yucheng11122017** [MarkBind/markbind#2347] opened 2023-07-26 15:32 UTC
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Tell us about your environment

Windows 10

### MarkBind version

5.0.1

### Describe the bug and the steps to reproduce it

Make a minimal panel 
```
<panel type="minimal">
hi
</panel>
```

Expand and collapse it once 
Expand it again

https://github.com/MarkBind/markbind/assets/77204346/416e832d-8c23-4d47-976c-06b92b1258c7

Code in minimal panel: 
```
    minimalToggle() {
      if (this.localExpanded) {
        /*
          This is a collapse.
          Set isHeaderAtBottom to true only at the end of transition.
          So that we can achieve the correct collapse transition effect of minimal panel.
        */
        const onCollapseDone = (event) => {
          if (event.target === this.$refs.panel) {
            this.isHeaderAtBottom = false;
            this.$refs.panel.removeEventListener('transitionend', onCollapseDone);
          }
        };
        this.$refs.panel.addEventListener('transitionend', onCollapseDone);
      } else {
        // This is an expansion. Set isHeaderAtBottom to true *immediately*.
        this.isHeaderAtBottom = true;
      }
      this.toggle();
    },
```
The onCollapseDone is only triggered upon the second expansion which results in this odd behavior

### Expected behavior

Expected: header will be at the top at the first collapse
Actual: header is missing 

Expected: that the header will be at the bottom at the second expansion 
Actual: the header is at the top at the second expansion

**Comment by jmestxr** [comment] 2023-08-09 17:32
It seems like the `isHeaderAtBottom` prop is redundant in `MinimalPanel.vue`, as it's merely a copy of `localExpanded`. The behavior of MinimalPanel seems to remain unchanged simply by replacing all instances of `isHeaderAtBottom` with `localExpanded`. The bug can be resolved particularly by changing line 44:

<img width="935" alt="Screenshot 2023-08-10 at 1 28 46 AM" src="https://github.com/MarkBind/markbind/assets/87931905/82bba950-edbf-4b03-9576-736cf0a48179">

<br><br>

P.S. I'm new to vue and MarkBind so pardon me if I'm wrong here :pray:

**Comment by jmestxr** [comment] 2023-08-17 06:59
**Update:** Previously I could reproduce the bug but I don't know why suddenly it seems to be working fine now. I'm on the latest master branch and using macOS.


https://github.com/MarkBind/markbind/assets/87931905/050876b7-d6f5-4590-ac5d-fac7ed8e7fd5

**Comment by Tim-Siu** [comment] 2024-02-01 11:29
I was unable to reproduce the error as well. It seems that the updates in the commit titled 'Add commit animation when closing panel with bottom switch (#2340)' by @yucheng11122017 have altered the behavior. Before this commit, the bug was indeed present. Should we consider closing this issue now?

https://github.com/MarkBind/markbind/assets/61866948/1c0de686-68d9-43ad-9336-28eb1c925c5c

**Comment by kaixin-hc** [comment] 2024-02-14 15:13
Thanks for the investigation @jmestxr and @Tim-Siu ! Since the bug doesn't seem to be present any more, I'll close the issue; appreciate the help in investigating

**Closed by kaixin-hc** 2024-02-14 15:13 UTC
Labels: c.Bug 🐛, p.Medium, help wanted
