### ISSUE TITLE
The embeds section in the User Guide is causing several bugs.

### ISSUE THREAD

**Issue by SPWwj** [MarkBind/markbind#2317] opened 2023-06-30 16:59 UTC
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Any related issues?

#1952

### Tell us about your environment

Window 10

### MarkBind version

 v4.1.0

### Describe the bug and the steps to reproduce it

- Navigate to the embeds section of the User Guide.
- Open the web console.

<img width="654" alt="image" src="https://github.com/MarkBind/markbind/assets/30100720/0c297b15-51ab-459c-828e-4ae7375edcc2">

### Expected behavior

Ideally, no errors or warnings should appear in the web console.

**Comment by tlylt** [comment] 2023-07-01 13:47
I recall seeing some of the warnings since early versions of MarkBind. I don't think they are bugs from a user's POV? (Are you observing any specific errors of embed directly related to the warnings/errors you screenshotted above? If so please specify)

> Any related issues?
https://github.com/MarkBind/markbind/issues/1952, https://github.com/MarkBind/markbind/issues/1952

typo here?

**Comment by SPWwj** [comment] 2023-07-02 03:38
> I recall seeing some of the warnings since early versions of MarkBind. I don't think they are bugs from a user's POV? (Are you observing any specific errors of embed directly related to the warnings/errors you screenshotted above? If so please specify)

Other than the screenshot above, did not see any user related bug

> > Any related issues?
> > #1952, #1952

Nope. just that they are on same feature, might be related to each other.

**Comment by damithc** [comment] 2023-07-02 05:16
> > Any related issues?
> > #1952, #1952
> 
> typo here?

@SPWwj You gave the same issue twice.

**Comment by ang-zeyu** [comment] 2023-07-04 15:40
No bug here but it is still worth investigating before it becomes one 💥

**Comment by WillCWX** [comment] 2023-07-06 14:33
It looks like these are just caused by third party cookies from Youtube and Microsoft. They should be sending / requesting analytics. Could it be that your `adblock` potentially blocked them for you? For me, the `GET/Access` errors stopped when I disabled mine.

The other warnings / `viewPreview` errors are because of how embeds work (specifically how Microsoft embeds powerpoints).
(they dump an entire html document under the `iframe` that may re-register some icons or have some weird permissions-policy)
It seems like the `viewPreview` class is missing from Microsoft's own embed scripts.

The fix maybe to seek a library that implements embeds better than simply using `iframe` or using `iframe`'s `sandbox` attribute to restrict unwanted behaviors.

Although as mentioned, the fix may not be required at all since the content is still available to users without visible errors.

**Comment by kaixin-hc** [comment] 2024-01-26 08:37
Given the investigation by @WillCWX , I've removed the ToInvestigate tag. 

If the errors are due to third party cookies as well as the way the embeds work, and there is no visible error to the user, I propose we close this issue for now as not a priority. If we find other issues with iframe embeds and look at moving away from them, we can reopen this issue then.

**Closed** 2024-02-01 07:55 UTC
Labels: p.Low
