### ISSUE TITLE
Build console progress bar doesn't show when using 'gitbash on Windows' terminals

### ISSUE THREAD

**Issue by yamgent** [MarkBind/markbind#416] opened 2018-08-03 12:55 UTC
**Tell us about your environment**

* **MarkBind Version:** 1.12.0

**What did you do? Please include the actual source code causing the issue.**
When building pages, a progress bar is shown. However, when using gitbash on Windows terminals (or any mintty terminals), the progress bar does not show.

Issue is related to https://github.com/visionmedia/node-progress/issues/170.

**What did you expect to happen?**
<img src="https://user-images.githubusercontent.com/3168908/43643703-c964004c-975e-11e8-8855-bf2f0f87b56d.png" width="500" />

**What actually happened? Please include the actual, raw output.**
<img src="https://user-images.githubusercontent.com/1673303/43637473-bda3de38-9747-11e8-8648-180d2044790d.png" width="350" />

**Comment by Xenonym** [comment] 2018-12-18 06:31
The fix for visionmedia/node-progress#170 has been merged, but the bug still happens even on `progress@2.0.3`, which includes the fix. Thus, that doesn't seem to be the cause.

After some investigation, it seems like this bug is actually related to visionmedia/node-progress#110. The PR referenced in the issue visionmedia/node-progress#168 fixes the issue with the `forceTTY` option, but it has not yet been merged.

**Comment by tlylt** [comment] 2021-08-18 11:35
Hello,

I tried running `npm run test` in `markbind/packages/cli` to check whether the built progress bar is shown correctly.
I'm using Windows 10 btw.
- cmd with Vscode: works
- bash within Vscode: works
- bash terminal: works
- cmd terminal (via windows terminal): works

Not sure if the issue has already been resolved. If the issue is related to the bug referenced in [the above comment](https://github.com/MarkBind/markbind/issues/416#issuecomment-448112057), then a quick patch is possible, as suggested [here](https://github.com/visionmedia/node-progress/issues/179#issuecomment-445274507). If not perhaps we can safely close this issue:)

**Comment by ang-zeyu** [comment] 2021-08-19 04:27
Thanks for investigating this! @tlylt Good to see it works on a whole bunch of terminals.

I'm still able to produce this via gitbash running on mintty 3.5, although strangely wsltty works fine.

In any case, I think this issue is a little out of our control. Rather maybe we could insert a one / 2 liner into the `gettingStarted` section in the documentation to recommend some terminals that are known to work.

**Comment by tlylt** [comment] 2021-08-19 11:25
> Thanks for investigating this! @tlylt Good to see it works on a whole bunch of terminals.
> 
> I'm still able to produce this via gitbash running on mintty 3.5, although strangely wsltty works fine.
> 
> In any case, I think this issue is a little out of our control. Rather maybe we could insert a one / 2 liner into the `gettingStarted` section in the documentation to recommend some terminals that are known to work.

Hi @ang-zeyu, hmm I am not familiar with terminals or console stuff, but I could try to apply the patch as suggested by others facing similar issues and send up a PR for you to verify if that works for "gitbash on mintty 3.5". Do you think that will be ok?

Alternatively, I can add a note in the docs to warn users (perhaps as a footnote in the getting started section). 
I think overall the user experience is not greatly impacted by this issue.

**Comment by ang-zeyu** [comment] 2021-08-19 13:00
> apply the patch as suggested by others

👀

if its fixable, let's try that!

> gitbash on mintty 3.5

it should come packaged in the latest version from here:
https://git-scm.com/downloads

**Comment by tlylt** [comment] 2021-08-20 01:43
> > apply the patch as suggested by others
> 
> 👀
> 
> if its fixable, let's try that!
> 
> > gitbash on mintty 3.5
> 
> it should come packaged in the latest version from here:
> https://git-scm.com/downloads

Hi @ang-zeyu , could you help verify if it works with https://github.com/MarkBind/markbind/pull/1654 pls?
I am unable to reproduce the result even though I think I am using gitbash coming from git. I tried git-bash and git-cmd and both are fine **with or without** the fix:
![image](https://user-images.githubusercontent.com/41845017/130165762-9017dde3-dfcd-4e67-981b-a0ee9dc0660c.png)

**Comment by ang-zeyu** [comment] 2021-08-21 08:01
@tlylt no dice, still no progress bar on your PR branch:

![ss](https://user-images.githubusercontent.com/3306138/130315111-8c995795-b365-4505-b463-dc88203ed495.png)

**Comment by ang-zeyu** [comment] 2021-08-21 08:07
> ![image](https://user-images.githubusercontent.com/41845017/130165762-9017dde3-dfcd-4e67-981b-a0ee9dc0660c.png)

Might be mistaken but the terminal in your screenshot dosen't seem like the default mintty that comes with the git installation as well (blue bar on top). Might be what's causing a false positive 🤔

**Comment by tlylt** [comment] 2021-08-21 11:08
Hi @ang-zeyu, thank you for your kind help in verifying the PR. I finally made some progress on this :)

For the false positive, it might be due to the fact that I did not choose the option with mintty when installing git (see screenshot below):
![image](https://user-images.githubusercontent.com/41845017/130319628-f63c6173-00eb-492d-b73b-3336350e2a55.png)

I did that because some tutorials that I have seen recommended the second option for windows 10, as the introduction of windows terminal and wsl probably makes working with cli easier nowadays.

I have tested on my laptop and I was getting the same result as you, probably because on my laptop I went with the default git installation.

On further inspection of the patch code, I found out that I misunderstood the fix PR raised over at node-progress and I did not invoke the code properly (Big warning for me to be caution with code that I don't understand fully 😂 ). I have updated the patch and verified that it works on my laptop. 

I shall continue the conversation over on my patch PR and make it ready to merge soon:)

**Closed** 2021-09-12 15:52 UTC
Labels: c.Bug 🐛, p.Low, s.ToInvestigate
