### ISSUE TITLE
Level 4 headings not showing up in search results

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#336] opened 2018-07-14 11:57 UTC
v1.9.0
context: https://nus-cs2103.github.io/website-base/
I've set search indexing to level 4 https://github.com/nus-cs2103/website-base/blob/master/site.json

In the case below, the [level 4 heading `Objects as Abstractions`](https://nus-cs2103.github.io/website-base/se-book-adapted/chapters/oop.html#objects-as-abstractions) did not show up in results.
![image](https://user-images.githubusercontent.com/1673303/42724150-8f8d7e1c-879f-11e8-81d4-bed640a1d32e.png)

Furthermore, some odd entries with `%` show up in results.

**Comment by yamgent** [comment] 2018-07-16 01:06
> In the case below, the level 4 heading Objects as Abstractions did not show up in results.

One possible reason could be that because the content is contained inside a panel, and the panel itself is dynamic, so the content wasn't loaded in when the headings were scanned, and we didn't pick it up as a result.

**Comment by damithc** [comment] 2018-07-16 02:30
> One possible reason could be that because the content is contained inside a panel, and the panel itself is dynamic, so the content wasn't loaded in when the headings were scanned, and we didn't pick it up as a result.

hmm... I thought index building is not dependent on page loading. Isn't the index built even before a single page is loaded?

**Comment by yamgent** [comment] 2018-07-16 02:34
> Isn't the index built even before a single page is loaded?

Yes, that is correct. What I meant is that, the index is built with reference to the html pages generated by MarkBind during a `markbind build`, and if a panel is dynamic, then the headings won't be visible on the html source.

**Comment by damithc** [comment] 2018-07-16 03:15
I see. I guess this affects nested panels of 2nd level and below (as the heading is specified in the panel text).
But these are expanded panels, which means they are effectively non-dynamic?

**Comment by Chng-Zhi-Xuan** [comment] 2018-07-16 03:21
Expanded Panels are still dynamic. 

The HTML will be removed when you close them. The difference is that since `expanded = true`, the HTML contents will be there when loaded and the algorithm in `setup.js` will index the headings. 

The reason it only affects 2nd level and below is because the first level's panel header will always be rendered. Since the 2nd level and below is contained within the 1st level's body, it is dynamically rendered when opened.

**Comment by nusjzx** [comment] 2018-07-16 03:34
cannot reproduce the %% problem. https://nusjzx.github.io/website-base/

**Comment by yamgent** [comment] 2018-07-16 04:21
Regarding the `%%` problem, can't reproduce this problem on a blank-slate website either, since MarkBind resolves the formatting before we start building the search index, so the raw `%%` syntax should be long gone by then.

`index.md`:
```markdown

# %%Dimmed%% heading (Level 1)
Hello world

## **Bold** heading! (Level 2)
Bye world

### ==Level 3== heading
Deeper
```

**Result:**

<img src="https://user-images.githubusercontent.com/3168908/42742925-fd8f87e0-88f1-11e8-92df-4cfce35b8a13.png" width="450"/>

**Comment by damithc** [comment] 2018-07-16 04:52
Roll back the website-base to a version around the time I posted this issue?

**Comment by yamgent** [comment] 2018-07-16 05:58
@nusjzx I found this problem at commit nus-cs2103/website-base@ed2ac01a3.

**Comment by nusjzx** [comment] 2018-07-16 05:59
noted

**Comment by yamgent** [comment] 2018-07-19 07:37
Current progress in this issue: After discussion as a team, we came to the conclusion that it will take a lot more effort than previously thought in order to implement the feature that makes the [level 4 heading `Objects as Abstractions` inside oop.html](https://nus-cs2103.github.io/website-base/se-book-adapted/chapters/oop.html#objects-as-abstractions) searchable. (This header is included inside a panel through `src`.)

This is because the content of the panel is not included inside the final generated `oop.html` file (where our current implementation collects the heading from), but generated as a separate `abstraction_text_include_.html` file (assuming the source is `abstraction_text.md`). Therefore, to collect the heading inside the panel, we must trace through all the `<panel>` tags in `oop.html` to find `abstraction_text_include_.html`, then traverse into this `abstraction_text_include_.html` file in order to search for more headings. This will require substantive changes to the post-processing logic in MarkBind.

---

An alternative is to explicitly include the source file such that the headings are already in the final generated `oop.html`, like so:

```html
<panel expanded>
   <include src="abstraction_text.md" />
</panel>
```

Instead of this:
```html
<panel src="abstraction_text.md" expanded>
</panel>
```

**Comment by yamgent** [comment] 2018-07-19 09:00
Further investigation seems to show that some `*_include_.html` files does not seem to exist when it is time to collect the headings, even though the collection is done after `Page#resolveDependency()` finishes its execution. `resolveDependency()` is responsible for generating the `*_include_.html`. Will need to probe the code further to find out what is going on.

**Comment by yamgent** [comment] 2018-07-24 07:41
Relevant PRs have been merged, and a quick test shows that `Objects as Abstractions` is now searchable. Closing issue...

**Closed by yamgent** 2018-07-24 07:41 UTC
Labels: f-Search, p.High
