### ISSUE TITLE
MarkBind Documentation is not navigable on mobile devices

### ISSUE THREAD

**Issue by Chng-Zhi-Xuan** [MarkBind/markbind#727] opened 2019-02-21 10:46 UTC
* **MarkBind Version:** v1.19

**Issue:**

Currently `site-nav` collapses completely when the screen width is less than **(max-width: 575.98px)**, which is Bootstrap's smallest responsive break-point.

However, since `site-nav` contents are not duplicated within the top `<navbar>`, thus the user is unable to navigate to other pages within the documentation.

As shown here |
--- |
![mobile-view](https://user-images.githubusercontent.com/31084833/53162667-76f5c500-3607-11e9-8962-cccf4ac4d655.PNG) |

<br>

**Solutions**

- Reduce **(max-width: 575.98px)** such that it has proper coverage for mobile devices 
  - ➕ Quickest fix
  - ➖ Not the best looking
  - ➖ Have a magic number within `site-nav.css`
- Render a [floating action button](https://material.io/design/components/buttons-floating-action-button.html) to expand the site navigation once the screen is smaller than **(max-width: 575.98px)**.
  - ➕ Aesthetically pleasing
  - ➕ Can be used for **(max-width: 575.98px)** responsive break-point instead of the current design
  - ➖ Longer implementation time
  - ➖ Blocks content underneath it

**Comment by acjh** [comment] 2019-02-21 12:56
Duplicate of #591

**Closed** 2019-02-22 02:02 UTC
Labels: a-Documentation 📝, f-SiteNav
