### ISSUE TITLE
Is there a more concise way to specify file exclusions in site.json?

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#715] opened 2019-02-20 10:53 UTC
Is there a way to make the following site.json setting more concise?

```json
    {"glob": "se-book-adapted/common/*.md"},
    {"glob": "book/combined/exercises.md"},
    {"src": "se-book-adapted/print.md",
      "searchable": "no"
    },
    {"glob": "se-book-adapted/chapters/architecture.md",
      "searchable": "no"
    },
    {"glob": "se-book-adapted/chapters/cppToJava.md",
      "searchable": "no"
    },
    {"glob": "se-book-adapted/chapters/designApproaches.md",
      "searchable": "no"
    },
    {"glob": "se-book-adapted/chapters/designPatterns.md",
      "searchable": "no"
    },
    {"glob": "se-book-adapted/chapters/gitAndGithub.md",
      "searchable": "no"
    },
    {"glob": "se-book-adapted/chapters/javaTools.md",
      "searchable": "no"
    },
    {"glob": "se-book-adapted/chapters/junit.md",
      "searchable": "no"
    },
    {"glob": "se-book-adapted/chapters/principles.md",
      "searchable": "no"
    },
    {"glob": "se-book-adapted/chapters/intellij.md",
      "searchable": "no"
    }
```

More generally, if the folder has 100 files and if we want to exclude 20 of them, is there a way to do that concisely?

**Comment by ang-zeyu** [comment] 2020-03-22 08:09
Would supporting a global `globExclude` option be sufficient?
using `searchable: "no"` might not be a good idea to exclude the file since it would still cause it to build, increasing build times

```
{
  "glob": "**/*.md"
},
{
  "globExclude": [ "se-book-adapted/chapters/intellij.*", "se-book-adapted/chapters/principles.md", ... ]
}
```

We could also have glob-specific exclusions since the directory walker we use supports it, e.g.

```
{
  "glob": "**/*.md",
  "exclude": [ "se-book-adapted/chapters/intellij.md", "se-book-adapted/chapters/principles.md", ... ]
}
```

**Comment by damithc** [comment] 2020-03-22 08:47
Yes, something like this could work.
```json
{
  "glob": "**/*.md",
  "exclude": [ "se-book-adapted/chapters/intellij.md", "se-book-adapted/chapters/principles.md", ... ]
}
```
More generally, something like this?
```
{
  "glob-include": ["**/*.md", ...]
  "glob-exclude": ["se-book-adapted/chapters/*.md",  ... ]
}
```

**Comment by acjh** [comment] 2020-03-22 10:03
Possible duplicate of #228

**Comment by ang-zeyu** [comment] 2020-03-22 11:46
> Yes, something like this could work.

👍 

I think it might be good to keep the current option name of `glob` and not `glob-include` for backwards compatibility though.
`exclude` could be `glob-exclude`.

Should the global exclude property be included as well? e.g. something like
```
{
   'pages': [ ... ],
   'pages-exclude': [ glob1, glob2, ... ]
}
```
mentioned in #228

**Comment by ryoarmanda** [comment] 2020-08-16 14:51
Hi, I am trying to take on this issue for my first one. I see the discussed approach is to have the exclusion declared per-entry, and there is also a question to have global exclusion. Just to clarify, as both achieve the same thing, is there any preference on which one to go for, or simply have both of them (albeit somewhat redundant)?

I feel that having global exclusion property might be easier for the user as they only have to write within one place versus per-entry exclusion, but I can also see some that would like to "group" up the exclusions based on the globs which in this case per-entry exclusion can provide.

```js
{
   'pages': [
        {
            'glob': 'glob1',
        },
        {
            'glob': 'glob2',
        },
    ],
    'pagesExclude': [
        'glob1exclude1',
        'glob1exclude2',
        'glob2exclude1',
        'glob2exclude2'
    ]
}
```

```js
{
   'pages': [
        {
            'glob': 'glob1',
            'globExclude': ['glob1exclude1', 'glob1exclude2']
        },
        {
            'glob': 'glob2',
            'globExclude': ['glob2exclude1', 'glob2exclude2']
        },
    ],
}
```

**Comment by ang-zeyu** [comment] 2020-08-16 15:51
> I feel that having global exclusion property might be easier for the user as they only have to write within one place versus per-entry exclusion, but I can also see some that would like to "group" up the exclusions based on the globs which in this case per-entry exclusion can provide.

I think we can provide both options and let the user choose which they prefer ^, also since the implementation changes required are small

If we don't see users using one or the either entirely we should drop it though. Might be good to get some usage opinions from @damithc for this!

**Comment by damithc** [comment] 2020-08-16 16:33
I'm OK to support both. Gives more flexibility to the user.

**Closed** 2020-08-18 16:01 UTC
Labels: a-AuthorUsability, a-Build, d.easy, good first issue, p.Low
