### ISSUE TITLE
Code blocks: inconsistent light/dark mode use when printing

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1401] opened 2020-12-02 12:36 UTC
v2.17.0

current: inline code remain in dark mode while regular code blocks change to light mode
suggested: both should use the light mode for printing

![image](https://user-images.githubusercontent.com/1673303/100873210-eb001500-34dd-11eb-9341-2c5fc9ab0b53.png)

**Comment by raysonkoh** [comment] 2020-12-04 21:16
I am unable to reproduce this locally with Markdown v2.17.0. May I know what is the value of `codeTheme` set to in `site.json` and could you provide an extract of the markdown code for that section?

**Comment by damithc** [comment] 2020-12-05 02:46
> I am unable to reproduce this locally with Markdown v2.17.0. May I know what is the value of `codeTheme` set to in `site.json` and could you provide an extract of the markdown code for that section?

The problem appears when you convert a page to PDF, using [this technique](https://se-education.org/guides/tutorials/savingPdf.html). In the PDF (meant for printing), all code should use the light background even if using the dark background in the web page.

Let me know if you still can't reproduce.

**Comment by ang-zeyu** [comment] 2020-12-05 03:17
should we just remove / comment the dark style for inline code for now?

Since in an earlier issue its was agreed that it makes the site look 'patchy'. (then we can get dark style out in the docs as well)

Not sure if there would be a good use case for it though. If there is, perhaps we can additionally provide an `inlineCodeTheme` configuration

@ryoarmanda

**Comment by raysonkoh** [comment] 2020-12-05 06:42
I can reproduce this issue now. I suspect the issue might be when `codeTheme` is set to dark and how chrome saves the pdf with the `Background graphics` option checked.

The issue does not appear when `codeTheme` is set to light. (Refer to ss below)
![image](https://user-images.githubusercontent.com/16506539/101235963-e454e600-3707-11eb-8f28-3bd76257d43a.png)

**Comment by damithc** [comment] 2020-12-05 06:51
> The issue does not appear when `codeTheme` is set to light. (Refer to ss below)
> ![image](https://user-images.githubusercontent.com/16506539/101235963-e454e600-3707-11eb-8f28-3bd76257d43a.png)

Yes, that's expected. when the code theme is set to light, the printed version follows the same and there is no problem.
When the code theme is set to dark, the printed version is still supposed to switch back to the light theme (to save ink), and that switch is not happening for inline code (but works as expected for regular code blocks) -- that's the inconsistency raised by this issue. What missing is the inline code also switching to the light theme when printed.

**Comment by raysonkoh** [comment] 2020-12-05 07:41
I have some idea on how to implement a fix for this using CSS, can I take up this issue?

**Comment by damithc** [comment] 2020-12-05 07:48
> I have some idea on how to implement a fix for this using CSS, can I take up this issue?

Sure, have a go at it.

**Comment by raysonkoh** [comment] 2020-12-05 08:57
Hi all, my PR is ready for review.

**Closed** 2020-12-05 13:38 UTC
Labels: f-CodeBlocks, p.Medium
