### ISSUE TITLE
Improve mobile friendliness

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#343] opened 2018-07-16 02:49 UTC
v1.9.0

As reported by @acjh, our [dogfooding site](https://nus-cs2103.github.io/website-base/) doesn't look good on mobile devices. Too much padding?

**Comment by Chng-Zhi-Xuan** [comment] 2018-07-16 02:54
Duplicate of #335 

Some of the reasons (but not limited to):
1. `website-content` class has `width: 70%` which squishes the content.
2. Font size for headers / titles are too large.
3. Indentation of nested panels squishes everything even more

**Comment by damithc** [comment] 2018-07-16 05:32
I've set max-width to 800px and reduced the font size in the schedule page a bit.

**Comment by Chng-Zhi-Xuan** [comment] 2018-07-23 01:39
Close #343 via #335

**Closed by Chng-Zhi-Xuan** 2018-07-23 01:39 UTC
Labels: a-ReaderUsability, p.High
