### ISSUE TITLE
PageNav cannot handle duplicate headings

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#633] opened 2019-01-26 04:04 UTC
v1.17.0

Problem: If a page has the same heading multiple times, PageNav shows only the first one.

**Comment by Chng-Zhi-Xuan** [comment] 2019-01-26 07:21
Wouldn't this be expected behaviour? 

Since the browser can only jump to one unique heading using the anchor. Even if I am able to index duplicate headings within the page navigation list, clicking on all of them will jump to the same one (first one).

**Comment by damithc** [comment] 2019-01-26 08:30
> Wouldn't this be expected behaviour?
> 
> Since the browser can only jump to one unique heading using the anchor. Even if I am able to index duplicate headings within the page navigation list, clicking on all of them will jump to the same one (first one).

From the implementation POV, yes. From the author's POV, _why can't I have the same heading multiple times in the same page?_

It seems this problem does not appear in normal pages where all the duplicate headings are in the same physical file (in which case duplicate headings have unique anchors suffixed with an index) but appears in complicated pages such as https://nus-te3201.github.io/2019/se-book-adapted/chapters/codeQuality.html. probably beause the content comes from many different files and rendered in a piecemeal fashion.

**Comment by damithc** [comment] 2019-01-26 13:03
I guess this is a hard problem to solve. :-p

**Comment by kaixin-hc** [comment] 2024-01-25 07:54
I believe this might be fixed in the current markbind version, so I will close this issue:

https://github.com/MarkBind/markbind/assets/59471320/7345112f-a788-46fe-bd14-a76779734e35

**Closed by kaixin-hc** 2024-01-25 07:54 UTC
Labels: p.Low, f-PageNav
