### ISSUE TITLE
fontawsome icons don't show underlines to indicate modal/tooltip

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#995] opened 2020-01-25 03:52 UTC
v2.9.1

code:
```html
<trigger trigger="click" for="modal:context-target">:fas-info:</trigger> 
<trigger trigger="click" for="modal:context-target">no icon</trigger> 
```
output: 
![image](https://user-images.githubusercontent.com/1673303/73115926-f18e3980-3f68-11ea-8df3-58b2bd11d2dd.png)

problem: note how the underline is missing from the first trigger

**Comment by hcwong** [comment] 2020-02-01 04:39
Hello Markbind peeps, can I take this?

**Comment by ang-zeyu** [comment] 2020-02-01 07:04
> Hello Markbind peeps, can I take this?

👍 Don't think anyone's working on this

A simple way to implement this would be to wait for https://github.com/MarkBind/markbind/pull/975 to get merged ( approved already ), then you would whitelist the `<trigger>` component in `componentParser` and do some processing there to look for rendered `:fa:` icons and add `fa-underline`.

Otherwise you could use jquery to look for it at runtime and add `fa-underline`, but to minimize rendering time I think this should be avoided.

Another thing to note would be (octicons)[https://github.com/MarkBind/markbind/pull/1000], but maybe it should be done in that pr itself. Could check with @dvrylc for this.

**Comment by ang-zeyu** [comment] 2020-02-01 07:28
Ignore the extra stuff earlier, could just do this with css.

Might check if it works for [octicons](https://github.com/MarkBind/markbind/pull/1000) though

**Comment by hcwong** [comment] 2020-02-02 09:30
Hmmm I'm going to change tooltip and trigger components: changing the underline style from `text-decoration: underline dashed` to `border bottom: 1px dashed black`. Is this okay?

**Comment by ang-zeyu** [comment] 2020-02-03 04:12
Sounds good; Might wanna try `currentColor` instead of `black` to keep the same underline color though

**Comment by damithc** [comment] 2020-03-12 10:16
This feature seems to be broken again. See https://nus-cs2113-ay1920s2.github.io/website/admin/participation-dashboard.html

**Comment by hcwong** [comment] 2020-03-12 13:23
@damithc is it the A0xxxxx values in the table?

**Comment by damithc** [comment] 2020-03-12 13:33
> @damithc is it the A0xxxxx values in the table?

Close. It's the ℹ️ icon that comes after the partial matric number. Clicking on it opens a modal, which means there should be a dotted line under it.

**Comment by hcwong** [comment] 2020-03-12 14:24
I see, I tried finding the page on https://github.com/nus-cs2113-AY1920S2/website, but cant seem to find it. Is there anywhere I can find it to help debug?

**Comment by damithc** [comment] 2020-03-12 14:54
It's in the `cs2113` branch. https://github.com/nus-cs2113-AY1920S2/website/blob/cs2113/admin/tp-progress-dashboard-table.mbdf

**Comment by hcwong** [comment] 2020-03-12 14:55
Thanks will debug and get back to you on this

**Comment by hcwong** [comment] 2020-03-16 16:19
Hey @damithc, just an update from me, this is a regression bug caused by this commit: https://github.com/MarkBind/markbind/commit/f215eeedac66e08cbee9f79c0573a566f4480f40.

Also, not sure, but for the 2113 website, I think the student number `A018XXXX` should be within the `<trigger>` blocks if its meant to be underlined, unless thats the intended behaviour.

**Comment by damithc** [comment] 2020-03-16 16:25
> Hey @damithc, just an update from me, this is a regression bug caused by this commit: [f215eee](https://github.com/MarkBind/markbind/commit/f215eeedac66e08cbee9f79c0573a566f4480f40).

I see. How to fix?

> Also, not sure, but for the 2113 website, I think the student number `A018XXXX` should be within the `<trigger>` blocks if its meant to be underlined, unless thats the intended behaviour.

Thanks for the heads up. Only the icon is supposed act as the trigger, so it's all good.

**Comment by hcwong** [comment] 2020-03-16 16:26
@openorclose, don't have much context on the commit, but seems like changing the `.trigger` class in markind's css restores the intended behavior. If this works, I'll submit the fix.

**Comment by openorclose** [comment] 2020-03-16 21:33
> @openorclose, don't have much context on the commit, but seems like changing the `.trigger` class in markind's `asset/css` back to `border-bottom: 1px dashed currentColor` restores the intended behavior. If this is fine by you, I'll submit the fix.

Sure, thanks!

> Also, it seems like the mounted() code in `trigger` is made redundant by the commit. Should i remove it as well?

 https://github.com/MarkBind/vue-strap/pull/135 nah there's already a pr to delete triggers and the other unneeded components

**Closed** 2020-03-30 04:22 UTC
Labels: c.Bug 🐛, f-Icons, p.Medium
