### ISSUE TITLE
The collapsed page nav appears in the print view

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#2157] opened 2023-02-11 15:34 UTC
Problem: When printing to PDF from a page that has a collapsed page navigation menu, the hamburger menu appears in the print view. Given below is an example.

Browser view:
![image](https://user-images.githubusercontent.com/1673303/218266904-17753385-fb88-4aec-b43f-e676b5d89088.png)

Print view:
![image](https://user-images.githubusercontent.com/1673303/218266802-17daa622-7834-485d-8063-c9856c44c396.png)

The problem doesn't happen if the page nav is not collapsed.

Expected: page nav should not appear in the print view, collapsed or otherwise.

**Comment by jovyntls** [comment] 2023-02-11 15:59
May be related to #2109 with the white navbar appearing in print

**Comment by Tim-Siu** [comment] 2024-02-04 14:38
I am not able to reproduce this error. It seems to have been solved with #2069.
<img width="1402" alt="Screenshot 2024-02-04 at 22 36 27" src="https://github.com/MarkBind/markbind/assets/61866948/d8d8040e-5abd-478a-b0bf-1dccf7e01e72">

**Comment by EltonGohJH** [comment] 2024-02-06 11:59
@Tim-Siu 
Thanks for the investigation. You are right and that this is resolved with #2069.
I will close this issue.

**Closed** 2024-02-06 12:00 UTC
Labels: c.Bug 🐛, f-TopNav
