### ISSUE TITLE
Tooltip formatting doesn't work on code

### ISSUE THREAD

**Issue by kaixin-hc** [MarkBind/markbind#1790] opened 2022-02-23 16:33 UTC
If it is using code formatting, the dotted underline does not appear for tooltips. Examples: 

<img width="100" alt="tooltips on code don't have useful visual cue" src="https://user-images.githubusercontent.com/59471320/155362337-1274e90f-cf62-427b-b8d3-aa8eb1409837.png">  (from a course website but I can't remember where : (
<img width="739" alt="tooltip formatting" src="https://user-images.githubusercontent.com/59471320/155363208-0f163ad7-322b-409c-bb2f-ff81a7094fa9.png">

**What did you expect to happen?**
I expected it to still have the dotted underline, which would suggest that I should mouse over it.

**What actually happened? Please include the actual, raw output.**
There is no indication that there is a tooltip.

Reproducing: `<tooltip content="Lorem ipsum dolor sit amet" placement="top">`Some text`</tooltip>`

**Comment by ryoarmanda** [comment] 2022-02-23 18:52
Good catch @kaixin-hc! Confirmed, the popover dotted underline is not visible on both codeblock themes. It is actually there, but covered by the background of the code.

**Comment by ang-zeyu** [comment] 2022-02-24 03:36
duplicate of #1231

**Closed by ang-zeyu** 2022-02-24 03:36 UTC
Labels: p.Medium, a-Style, f-Tooltip, d.easy
