### ISSUE TITLE
Trigger decoration extend to next space

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#19] opened 2017-03-30 12:00 UTC
This space is not inside the trigger text, but is underlined.

![image](https://cloud.githubusercontent.com/assets/1673303/24503173/84703ae0-1583-11e7-820f-476813a2052c.png)

**Comment by Gisonrg** [comment] 2017-03-30 12:20
I have fixed this. This is not a bug with the library though, but rather about the HTML and CSS. 
It is quite interesting because whether writing include a new line seems matter for `border-bottom`, as can be seen in this [example](https://jsbin.com/rosizijazu/2/edit?html,output)

**Comment by damithc** [comment] 2017-03-31 04:13
Now the space is deleted altogether. 😛

**Comment by damithc** [comment] 2018-02-03 11:06
> I couldn't reproduce this.

I think this is the same case as spaces around formatted text getting deleted, reported as a separate issue. Although it doesn't happen all the time. May be fixed already?

**Comment by acjh** [comment] 2018-02-03 11:08
Yes, fixed in #90.

**Closed** 2018-02-03 11:26 UTC
