### ISSUE TITLE
Modals: The x button position is off

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#2473] opened 2024-03-24 14:53 UTC
The `X` seems too close to the edge?

![image](https://github.com/MarkBind/markbind/assets/1673303/859cff1f-e325-4024-906d-e2a50619509d)

**Comment by tlylt** [comment] 2024-03-26 13:11
Link to the location of this particular modal? Modals on the MarkBind docs seem ok
![image](https://github.com/MarkBind/markbind/assets/41845017/236475ef-5f3b-4244-9a25-24088f065ecc)

**Comment by damithc** [comment] 2024-03-26 13:16
> Link to the location of this particular modal? Modals on the MarkBind docs seem ok

Hmm... in fact, I started noticing this only recently myself. 

Try https://nus-cs2103-ay2324s2.github.io/website/schedule/week10/project.html 

![image](https://github.com/MarkBind/markbind/assets/1673303/24bc69f7-e8ff-4617-b208-52106a914dcf)

I'm on Win 11, this appeared on Chrome, Edge, Firefox.

**Comment by EltonGohJH** [comment] 2024-03-26 13:58
Verified  that this issue exists on Mac OS chrome and also windows 11 Chrome.

**Comment by tlylt** [comment] 2024-03-26 14:09
This issue only occurs for dismissible box containing a modal via the include mechanism. The minimal reproducible example is as follows:

In `a.md`
```md
<box dismissible>

<include src="b.md#example" />

</box>
 ```

In `b.md`

```md
<div id="example">

<trigger for="modal-a">modal trigger</trigger>.

<modal header="modal header" id="modal-a" >
  Lorem ipsum
</modal>

</div>
```
![image](https://github.com/MarkBind/markbind/assets/41845017/7653d26c-f080-49f7-b4d1-53c67440129e)

The reason is because when modal is included inside a box via the include mechanism, the model content is part of the box element, hence resulting in this CSS selector `.alert-dismissible .btn-close` from Bootstrap modal to apply on the closing button, adding a `position:absolute` to it.

![image](https://github.com/MarkBind/markbind/assets/41845017/cf2aeaa7-a9cb-40fe-8982-b0097350e58e)

In the normal scenario, this selector won't apply:
![image](https://github.com/MarkBind/markbind/assets/41845017/7a46a82c-e402-419b-91c3-63b824470e00)

**Comment by damithc** [comment] 2024-03-26 14:31
> This issue only occurs for dismissible box containing a modal via the include mechanism.

I see. Thanks for the help with the investigation, @tlylt

**Closed** 2024-04-12 14:16 UTC
Labels: c.Bug 🐛, p.High, f-Modal, d.easy
